// <auto-generated />
using System;
using GymHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymHub.Data.Migrations
{
    [DbContext(typeof(GymHubDbContext))]
    [Migration("20230730165852_FixGroupActivityDescription")]
    partial class FixGroupActivityDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GymHub.Data.Models.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TraineeLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("ActivitiesCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Intensity = "Low",
                            TraineeLevel = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Intensity = "Moderate",
                            TraineeLevel = "Beginner"
                        },
                        new
                        {
                            Id = 3,
                            Intensity = "Moderate",
                            TraineeLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 4,
                            Intensity = "Moderate",
                            TraineeLevel = "Advanced"
                        },
                        new
                        {
                            Id = 5,
                            Intensity = "High",
                            TraineeLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 6,
                            Intensity = "High",
                            TraineeLevel = "Advanced"
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymHub.Data.Models.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("GymHub.Data.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd2fa2eb-2bce-482e-9f28-08a2a705b6c9"),
                            TraineeId = new Guid("efe69cd0-ff7a-4f5a-b038-18a62654c084"),
                            TrainingId = new Guid("63d1f1d6-9348-4710-8082-20a1fbf189e2")
                        },
                        new
                        {
                            Id = new Guid("4ce3627a-7ed9-460f-8954-e84bdf978a18"),
                            TraineeId = new Guid("efe69cd0-ff7a-4f5a-b038-18a62654c084"),
                            TrainingId = new Guid("3e154226-2820-4837-81c8-247e4604cdd6")
                        },
                        new
                        {
                            Id = new Guid("a95ee763-73af-4f1e-9942-30004ccdb826"),
                            TraineeId = new Guid("e89fc950-317b-454b-9c66-c082db3cbec2"),
                            TrainingId = new Guid("66afc146-91e8-461f-a9c2-8b61419f6af3")
                        },
                        new
                        {
                            Id = new Guid("b903e948-dbb2-4177-b9f1-5d2feb46f1a6"),
                            TraineeId = new Guid("f5c10860-7074-4121-ae6a-f8e6b832340b"),
                            TrainingId = new Guid("a2b6df44-832f-4ae2-ae77-4f8bc89a66af")
                        },
                        new
                        {
                            Id = new Guid("e88db467-0004-4e11-9d80-648316f73a31"),
                            TraineeId = new Guid("3ee69130-4ce4-450d-be65-0ab522760278"),
                            TrainingId = new Guid("492b5886-64cf-4f0e-9fdb-2baed606e361")
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountOfMaxSpots")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("GroupActivities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11"),
                            CategoryId = 6,
                            CountOfMaxSpots = 20,
                            Description = "Cross training is a diverse workout approach that involves mixing various exercises and activities to enhance overall fitness and prevent workout plateaus. By combining cardio, strength training, and flexibility exercises, it targets multiple muscle groups and reduces the risk of overuse injuries.",
                            Name = "Cross Training"
                        },
                        new
                        {
                            Id = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527"),
                            CategoryId = 3,
                            CountOfMaxSpots = 20,
                            Description = "Kickboxing is a high-intensity martial art and cardio workout that combines punching, kicking, and knee strikes. It improves overall fitness, endurance, and self-defense skills while providing a fun and challenging way to burn calories and relieve stress.",
                            Name = "Kickboxing"
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupActivityTrainer", b =>
                {
                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainerId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("GroupActivityTrainers");

                    b.HasData(
                        new
                        {
                            TrainerId = new Guid("ad716331-39a9-4ef2-88f2-0e69f7654ec1"),
                            ActivityId = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11")
                        },
                        new
                        {
                            TrainerId = new Guid("5b86293b-856f-47b8-8b93-63a3c7a965e1"),
                            ActivityId = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527")
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TraineeId");

                    b.ToTable("GroupEnrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("185f01bb-cb3d-4a44-a718-8da91b77a46a"),
                            ScheduleId = new Guid("da220d33-5a34-46a2-9e95-415aaafbe7cd"),
                            TraineeId = new Guid("3ee69130-4ce4-450d-be65-0ab522760278")
                        },
                        new
                        {
                            Id = new Guid("b4c5dd72-11d1-4f18-96b3-c03597a0d132"),
                            ScheduleId = new Guid("8d827ef7-962b-4a01-a391-88663ecac213"),
                            TraineeId = new Guid("efe69cd0-ff7a-4f5a-b038-18a62654c084")
                        },
                        new
                        {
                            Id = new Guid("db91e9ab-e05b-4121-b1dd-137d8ac80db9"),
                            ScheduleId = new Guid("8d827ef7-962b-4a01-a391-88663ecac213"),
                            TraineeId = new Guid("c4e34109-23ba-42a1-9a17-3797090de18c")
                        },
                        new
                        {
                            Id = new Guid("21fe6937-bd86-44af-8c25-3740756f3943"),
                            ScheduleId = new Guid("6104ae44-7737-4bfe-9146-969c78f8664b"),
                            TraineeId = new Guid("f5c10860-7074-4121-ae6a-f8e6b832340b")
                        },
                        new
                        {
                            Id = new Guid("9a28747c-0dd9-4a0f-b489-78c2ae91d8fb"),
                            ScheduleId = new Guid("b3a5cc92-fd09-4fe0-89a9-f6bd98bf90e1"),
                            TraineeId = new Guid("e89fc950-317b-454b-9c66-c082db3cbec2")
                        },
                        new
                        {
                            Id = new Guid("5ec7ebbf-9791-4607-a03c-5a0278a4ba88"),
                            ScheduleId = new Guid("b3a5cc92-fd09-4fe0-89a9-f6bd98bf90e1"),
                            TraineeId = new Guid("f5c10860-7074-4121-ae6a-f8e6b832340b")
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountOfTrainees")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("GroupSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ea2a2d0-10f6-4fff-a4a5-28ce33c5a5ec"),
                            ActivityId = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 8, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a9a81c48-7e25-469e-8f61-75b4669c1b4a"),
                            ActivityId = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 22, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 22, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8d827ef7-962b-4a01-a391-88663ecac213"),
                            ActivityId = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 11, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b3a5cc92-fd09-4fe0-89a9-f6bd98bf90e1"),
                            ActivityId = new Guid("0bb32c51-d799-4004-915f-91ccea62ce11"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 25, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1f607d8-e1e2-4ca8-9bda-caa1cfd0c31f"),
                            ActivityId = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6104ae44-7737-4bfe-9146-969c78f8664b"),
                            ActivityId = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("539d5620-f636-439c-a7d5-94f3b3654f70"),
                            ActivityId = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 21, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("da220d33-5a34-46a2-9e95-415aaafbe7cd"),
                            ActivityId = new Guid("6ad5a4d2-11fa-4fee-89e6-a341a47bf527"),
                            CountOfTrainees = 0,
                            EndTime = new DateTime(2023, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 8, 28, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.IndividualTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IndividualTrainings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63d1f1d6-9348-4710-8082-20a1fbf189e2"),
                            EndTime = new DateTime(2023, 8, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Intensity = "Low",
                            IsCanceled = false,
                            StartTime = new DateTime(2023, 8, 23, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3e154226-2820-4837-81c8-247e4604cdd6"),
                            EndTime = new DateTime(2023, 8, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Intensity = "High",
                            IsCanceled = false,
                            StartTime = new DateTime(2023, 8, 22, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("66afc146-91e8-461f-a9c2-8b61419f6af3"),
                            EndTime = new DateTime(2023, 8, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Intensity = "High",
                            IsCanceled = false,
                            StartTime = new DateTime(2023, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a2b6df44-832f-4ae2-ae77-4f8bc89a66af"),
                            EndTime = new DateTime(2023, 8, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Intensity = "Moderate",
                            IsCanceled = false,
                            StartTime = new DateTime(2023, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("492b5886-64cf-4f0e-9fdb-2baed606e361"),
                            EndTime = new DateTime(2023, 8, 18, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Intensity = "Moderate",
                            IsCanceled = false,
                            StartTime = new DateTime(2023, 8, 18, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.IndividualTrainingTrainer", b =>
                {
                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainerId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("IndividualTrainingsTrainers");

                    b.HasData(
                        new
                        {
                            TrainerId = new Guid("ad716331-39a9-4ef2-88f2-0e69f7654ec1"),
                            TrainingId = new Guid("63d1f1d6-9348-4710-8082-20a1fbf189e2")
                        },
                        new
                        {
                            TrainerId = new Guid("ad716331-39a9-4ef2-88f2-0e69f7654ec1"),
                            TrainingId = new Guid("3e154226-2820-4837-81c8-247e4604cdd6")
                        },
                        new
                        {
                            TrainerId = new Guid("e4c6589b-afa8-49c0-8d78-119d3ee95269"),
                            TrainingId = new Guid("66afc146-91e8-461f-a9c2-8b61419f6af3")
                        },
                        new
                        {
                            TrainerId = new Guid("0d61d878-2b3d-49bd-b4fb-ac482a7d9bda"),
                            TrainingId = new Guid("a2b6df44-832f-4ae2-ae77-4f8bc89a66af")
                        },
                        new
                        {
                            TrainerId = new Guid("0d61d878-2b3d-49bd-b4fb-ac482a7d9bda"),
                            TrainingId = new Guid("492b5886-64cf-4f0e-9fdb-2baed606e361")
                        });
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CountOfTrainees")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("GymHub.Data.Models.TrainerCertification", b =>
                {
                    b.Property<Guid>("CetrificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CetrificationId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerCertifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymHub.Data.Models.Enrollment", b =>
                {
                    b.HasOne("GymHub.Data.Models.Trainee", "Trainee")
                        .WithMany("Enrollments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.IndividualTraining", "IndividualTraining")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualTraining");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupActivity", b =>
                {
                    b.HasOne("GymHub.Data.Models.ActivityCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupActivityTrainer", b =>
                {
                    b.HasOne("GymHub.Data.Models.GroupActivity", "GroupActivity")
                        .WithMany("GroupActivitiesTrainers")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.Trainer", "Trainer")
                        .WithMany("GroupActivitiesTrainers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupActivity");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupEnrollment", b =>
                {
                    b.HasOne("GymHub.Data.Models.GroupSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.Trainee", "Trainee")
                        .WithMany("GroupEnrollments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupSchedule", b =>
                {
                    b.HasOne("GymHub.Data.Models.GroupActivity", "GroupActivity")
                        .WithMany("GroupSchedules")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupActivity");
                });

            modelBuilder.Entity("GymHub.Data.Models.IndividualTrainingTrainer", b =>
                {
                    b.HasOne("GymHub.Data.Models.Trainer", "Trainer")
                        .WithMany("IndividualTrainingTrainer")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.IndividualTraining", "IndividualTraining")
                        .WithMany("IndividualTrainingTrainer")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualTraining");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainee", b =>
                {
                    b.HasOne("GymHub.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainer", b =>
                {
                    b.HasOne("GymHub.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymHub.Data.Models.TrainerCertification", b =>
                {
                    b.HasOne("GymHub.Data.Models.Certification", "Certification")
                        .WithMany("TrainersCertifications")
                        .HasForeignKey("CetrificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.Trainer", "Trainer")
                        .WithMany("TrainerCertifications")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymHub.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Data.Models.Certification", b =>
                {
                    b.Navigation("TrainersCertifications");
                });

            modelBuilder.Entity("GymHub.Data.Models.GroupActivity", b =>
                {
                    b.Navigation("GroupActivitiesTrainers");

                    b.Navigation("GroupSchedules");
                });

            modelBuilder.Entity("GymHub.Data.Models.IndividualTraining", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("IndividualTrainingTrainer");
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainee", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GroupEnrollments");
                });

            modelBuilder.Entity("GymHub.Data.Models.Trainer", b =>
                {
                    b.Navigation("GroupActivitiesTrainers");

                    b.Navigation("IndividualTrainingTrainer");

                    b.Navigation("TrainerCertifications");
                });
#pragma warning restore 612, 618
        }
    }
}
